import { createHash, randomUUID } from "node:crypto";
import { readFile, readdir } from "node:fs/promises";
import { basename, join } from "node:path";
import { captureIdentity, validateAllowedPath, type PathIdentity } from "../filesystem.ts";
import { secureCreateDirectory, secureCreateNoReplace, secureRemoveDirectory, secureRenameDirectoryNoReplace } from "../native-filesystem.ts";
import { atomicRemove, ensureDirectoryTree, parseObject, requiredBytes } from "./mutation.ts";

export function processAlive(pid: number): boolean { try { process.kill(pid, 0); return true; } catch (error) { if ((error as NodeJS.ErrnoException).code === "ESRCH") return false; return true; } }

export async function reclaimStaleLock(lockPath: string, installationRoot: string): Promise<void> { await validateAllowedPath(lockPath, installationRoot, "directory"); const names = await readdir(lockPath); if (names.length !== 1 || names[0] !== "owner.json") throw new Error("transaction lock has invalid recovery metadata"); const ownerBytes = await requiredBytes(join(lockPath, "owner.json"), "transaction lock owner"); const owner = parseObject<{ schemaVersion: number; pid: number; token: string }>(ownerBytes, ["schemaVersion", "pid", "token"], "transaction lock owner"); if (owner.schemaVersion !== 1 || !Number.isSafeInteger(owner.pid) || owner.pid <= 0 || !/^[0-9a-f]{64}$/.test(owner.token)) throw new Error("transaction lock has invalid recovery metadata"); if (processAlive(owner.pid)) throw new Error("installation-root transaction lock is already active"); const parentIdentity = await captureIdentity(installationRoot); const identity = await captureIdentity(lockPath); const retiredName = `.transaction.lock.stale-${randomUUID()}`; const retired = join(installationRoot, retiredName); await secureRenameDirectoryNoReplace({ sourceDirectory: installationRoot, sourceName: basename(lockPath), sourceDirectoryIdentity: parentIdentity, sourceObjectIdentity: identity, destinationDirectory: installationRoot, destinationName: retiredName, destinationDirectoryIdentity: parentIdentity }); if (!(await requiredBytes(join(retired, "owner.json"), "transaction lock owner")).equals(ownerBytes)) throw new Error("transaction lock ownership changed"); await atomicRemove(join(retired, "owner.json"), identity, ownerBytes); await secureRemoveDirectory({ directory: installationRoot, name: retiredName, directoryIdentity: parentIdentity, objectIdentity: identity }); }

export async function withInstallationLock<T>(installationRoot: string, ancestorPath: string, ancestorIdentity: PathIdentity, action: () => Promise<T>, allowStaleRecovery = false): Promise<T> { const installationIdentity = await ensureDirectoryTree(ancestorPath, ancestorIdentity, installationRoot); const lockPath = join(installationRoot, ".transaction.lock"); try { await secureCreateDirectory({ directory: installationRoot, name: basename(lockPath), directoryIdentity: installationIdentity }); } catch (error) { if ((error as NodeJS.ErrnoException).code !== "EEXIST") throw error; if (!allowStaleRecovery) throw new Error("installation-root transaction lock is already active"); await reclaimStaleLock(lockPath, installationRoot); await secureCreateDirectory({ directory: installationRoot, name: basename(lockPath), directoryIdentity: installationIdentity }); } const lockIdentity = await captureIdentity(lockPath); const owner = Buffer.from(`${JSON.stringify({ schemaVersion: 1, pid: process.pid, token: createHash("sha256").update(randomUUID()).digest("hex") })}\n`); await secureCreateNoReplace({ directory: lockPath, name: "owner.json", directoryIdentity: lockIdentity }, owner); if (!(await readFile(join(lockPath, "owner.json"))).equals(owner)) throw new Error("transaction lock readback failed"); const cleanup = async (): Promise<void> => { await atomicRemove(join(lockPath, "owner.json"), lockIdentity, owner); await secureRemoveDirectory({ directory: installationRoot, name: basename(lockPath), directoryIdentity: installationIdentity, objectIdentity: lockIdentity }); }; try { const result = await action(); await cleanup(); return result; } catch (error) { try { await cleanup(); } catch { /* Preserve the primary transaction failure and never remove an untrusted replacement. */ } throw error; } }
