import { basename, dirname, join } from "node:path";
import { assertIdentity, captureIdentity, validateAllowedPath, type PathIdentity } from "../filesystem.ts";
import type { GovernanceBinding } from "../managed-block.ts";
import { verifyRelease } from "../release.ts";
import type { TransactionRequest } from "./contracts.ts";
import { digest, parseObject, requiredBytes } from "./snapshot.ts";
import { SEMVER } from "./version.ts";

export interface CurrentMetadata extends GovernanceBinding { readonly schemaVersion: 1; readonly targetRoot: string; readonly entryFile: string; }
export interface StoredPathIdentity { readonly device: string; readonly inode: string; readonly mode: number; }
export interface Receipt { readonly schemaVersion: 1; readonly id: string; readonly bindingId: string; readonly status: "PREPARED" | "COMMITTED" | "ROLLED_BACK"; readonly operation: "install" | "update" | "uninstall"; readonly backupRoot: string; readonly backupRootIdentity: StoredPathIdentity; readonly entryPath: string; readonly entryParentIdentity: StoredPathIdentity; readonly installationIdentity: StoredPathIdentity; readonly bindingRootIdentity: StoredPathIdentity; readonly releasesRootIdentity: StoredPathIdentity; readonly releaseIdentity: StoredPathIdentity | null; readonly entryExisted: boolean; readonly currentExisted: boolean; readonly releasePath: string; readonly releaseExisted: boolean; readonly localRulesPath: string | null; readonly localRulesParentIdentity: StoredPathIdentity | null; readonly localRulesExisted: boolean; readonly entryBackupDigest: string | null; readonly currentBackupDigest: string | null; readonly localRulesBackupDigest: string | null; readonly entryAppliedDigest: string; readonly currentAppliedDigest: string | null; readonly localRulesAppliedDigest: string | null; }

export const RECEIPT_KEYS = ["schemaVersion", "id", "bindingId", "status", "operation", "backupRoot", "backupRootIdentity", "entryPath", "entryParentIdentity", "installationIdentity", "bindingRootIdentity", "releasesRootIdentity", "releaseIdentity", "entryExisted", "currentExisted", "releasePath", "releaseExisted", "localRulesPath", "localRulesParentIdentity", "localRulesExisted", "entryBackupDigest", "currentBackupDigest", "localRulesBackupDigest", "entryAppliedDigest", "currentAppliedDigest", "localRulesAppliedDigest"] as const;
export const CURRENT_KEYS = ["schemaVersion", "version", "installationRoot", "governancePath", "manifestPath", "governanceDigest", "manifestDigest", "bundleDigest", "targetRoot", "entryFile"] as const;

export function storeIdentity(identity: PathIdentity): StoredPathIdentity { return { device: identity.device.toString(), inode: identity.inode.toString(), mode: identity.mode }; }

export function loadIdentity(value: StoredPathIdentity | null, label: string): PathIdentity | undefined { if (value === null) return undefined; if (typeof value !== "object" || Object.keys(value).sort().join("\0") !== "device\0inode\0mode" || !/^(0|[1-9]\d*)$/.test(value.device) || !/^(0|[1-9]\d*)$/.test(value.inode) || !Number.isSafeInteger(value.mode) || value.mode < 0) throw new Error(`transaction receipt has invalid ${label} identity`); return { device: BigInt(value.device), inode: BigInt(value.inode), mode: value.mode }; }

export function parseReceiptObject(bytes: Buffer): Receipt { return parseObject<Receipt>(bytes, RECEIPT_KEYS, "transaction receipt"); }

export function parseCurrentObject(bytes: Buffer): CurrentMetadata { return parseObject<CurrentMetadata>(bytes, CURRENT_KEYS, "current metadata"); }

export async function validateReceipt(bytes: Buffer, request: TransactionRequest, bindingId: string): Promise<Receipt> {
  const receipt = parseReceiptObject(bytes); const id = bindingId; const backupBase = join(request.installationRoot, "backups", id); const releases = join(request.installationRoot, "releases");
  loadIdentity(receipt.backupRootIdentity, "backup root"); loadIdentity(receipt.entryParentIdentity, "entry parent"); loadIdentity(receipt.installationIdentity, "installation"); loadIdentity(receipt.bindingRootIdentity, "binding root"); loadIdentity(receipt.releasesRootIdentity, "releases root"); const releaseIdentity = loadIdentity(receipt.releaseIdentity, "release"); const localRulesParentIdentity = loadIdentity(receipt.localRulesParentIdentity, "local rules parent");
  const digests = [receipt.entryBackupDigest, receipt.currentBackupDigest, receipt.localRulesBackupDigest, receipt.currentAppliedDigest, receipt.localRulesAppliedDigest];
  const scalar = typeof receipt.id === "string" && typeof receipt.bindingId === "string" && typeof receipt.backupRoot === "string" && typeof receipt.entryPath === "string" && typeof receipt.entryExisted === "boolean" && typeof receipt.currentExisted === "boolean" && typeof receipt.releasePath === "string" && typeof receipt.releaseExisted === "boolean" && typeof receipt.localRulesExisted === "boolean" && (receipt.localRulesPath === null || typeof receipt.localRulesPath === "string") && /^[0-9a-f]{64}$/.test(receipt.entryAppliedDigest) && digests.every((value) => value === null || typeof value === "string" && /^[0-9a-f]{64}$/.test(value));
  const expectedLocal = join(receipt.releasePath, "bundle", "agent-governance", (await verifyRelease(request.releaseRoot)).localRulesPath);
  if (!scalar || receipt.schemaVersion !== 1 || receipt.bindingId !== id || !/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(receipt.id) || !["PREPARED", "COMMITTED", "ROLLED_BACK"].includes(receipt.status) || !["install", "update", "uninstall"].includes(receipt.operation) || receipt.entryPath !== join(request.targetRoot, request.entryFile) || receipt.backupRoot !== join(backupBase, receipt.id) || dirname(receipt.releasePath) !== releases || !SEMVER.test(basename(receipt.releasePath)) || (receipt.localRulesPath !== null && receipt.localRulesPath !== expectedLocal) || (receipt.localRulesPath === null && receipt.localRulesExisted) || (receipt.localRulesPath === null) !== (localRulesParentIdentity === undefined) || receipt.entryExisted !== (receipt.entryBackupDigest !== null) || receipt.currentExisted !== (receipt.currentBackupDigest !== null) || receipt.localRulesExisted !== (receipt.localRulesBackupDigest !== null) || (receipt.localRulesPath === null) !== (receipt.localRulesAppliedDigest === null) || (receipt.releaseExisted || receipt.operation !== "uninstall") !== (releaseIdentity !== undefined) || (receipt.operation === "uninstall") !== (receipt.currentAppliedDigest === null)) throw new Error("transaction receipt has invalid values");
  return receipt;
}

export async function verifiedBackup(receipt: Receipt, request: TransactionRequest, name: string, expectedDigest: string): Promise<Buffer> { await validateAllowedPath(receipt.backupRoot, join(request.installationRoot, "backups", receipt.bindingId), "directory"); const value = await requiredBytes(join(receipt.backupRoot, name), `${name} backup`); if (digest(value) !== expectedDigest) throw new Error(`${name} backup digest mismatch`); return value; }

export async function validateBackupEvidence(receipt: Receipt, request: TransactionRequest): Promise<void> { const absent = digest(Buffer.from("absent\n")); if (receipt.entryBackupDigest === null) await verifiedBackup(receipt, request, "entry.absent", absent); else await verifiedBackup(receipt, request, "entry.bin", receipt.entryBackupDigest); if (receipt.currentBackupDigest === null) await verifiedBackup(receipt, request, "current.absent", absent); else await verifiedBackup(receipt, request, "current.json", receipt.currentBackupDigest); await verifiedBackup(receipt, request, "entry.applied.bin", receipt.entryAppliedDigest); if (receipt.currentAppliedDigest === null) await verifiedBackup(receipt, request, "current.applied.absent", absent); else await verifiedBackup(receipt, request, "current.applied.json", receipt.currentAppliedDigest); if (receipt.localRulesBackupDigest !== null) await verifiedBackup(receipt, request, "local-rules.bin", receipt.localRulesBackupDigest); if (receipt.localRulesAppliedDigest !== null) await verifiedBackup(receipt, request, "local-rules.applied.bin", receipt.localRulesAppliedDigest); }

export async function receiptWithMatchingBackup(bytes: Buffer, request: TransactionRequest, bindingId: string): Promise<Receipt> { const receipt = await validateReceipt(bytes, request, bindingId); await validateAllowedPath(receipt.backupRoot, join(request.installationRoot, "backups", receipt.bindingId), "directory"); await assertIdentity(receipt.backupRoot, loadIdentity(receipt.backupRootIdentity, "backup root")!); const backup = await requiredBytes(join(receipt.backupRoot, "receipt.json"), "backup receipt"); const backupReceipt = await validateReceipt(backup, request, bindingId); const immutableMatch = RECEIPT_KEYS.every((key) => key === "status" || JSON.stringify(receipt[key]) === JSON.stringify(backupReceipt[key])); const recoverableSplit = receipt.status === "COMMITTED" && ["PREPARED", "ROLLED_BACK"].includes(backupReceipt.status) || receipt.status === "PREPARED" && backupReceipt.status === "ROLLED_BACK"; if (!immutableMatch || (receipt.status === backupReceipt.status ? !bytes.equals(backup) : !recoverableSplit)) throw new Error("transaction receipt copies differ"); await validateBackupEvidence(receipt, request); return receipt; }
