import { constants } from "node:fs";
import { lstat, open, readdir } from "node:fs/promises";
import { basename, dirname, join } from "node:path";
import { assertIdentity, captureIdentity, type PathIdentity } from "../filesystem.ts";
import { secureCreateNoReplace, secureRenameNoReplace } from "../native-filesystem.ts";
import { verifyRelease } from "../release.ts";
import type { TransactionCheckpoint, TransactionRequest } from "./contracts.ts";
import { ConcurrentEntryChange, atomicCreate, atomicRemove, atomicWrite, exists, matchesSnapshot, optionalBytes, requiredBytes, sameFileSnapshot } from "./mutation.ts";
import { loadIdentity, parseCurrentObject, receiptWithMatchingBackup, verifiedBackup, type Receipt } from "./receipts.ts";

export async function otherBindingReferences(releasePath: string, installationRoot: string, bindingId: string): Promise<boolean> { const bindings = join(installationRoot, "bindings"); for (const name of await readdir(bindings)) { if (name === bindingId) continue; const root = join(bindings, name); const stat = await lstat(root); if (stat.isSymbolicLink() || !stat.isDirectory()) throw new Error("unsafe binding state directory"); const bytes = await optionalBytes(join(root, "current.json")); if (bytes === undefined) continue; const current = parseCurrentObject(bytes); if (join(installationRoot, "releases", current.version) === releasePath) return true; } return false; }

export function entryDetachPath(receipt: Receipt): string { return join(dirname(receipt.entryPath), `.${basename(receipt.entryPath)}.agent-governance-${receipt.id}.restore.bin`); }

export async function optionalDetachedEntry(receipt: Receipt): Promise<{ readonly bytes: Buffer; readonly identity: PathIdentity } | undefined> {
  const path = entryDetachPath(receipt); let handle: Awaited<ReturnType<typeof open>>; try { handle = await open(path, constants.O_RDONLY | constants.O_NOFOLLOW); } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return undefined; throw error; }
  try { const opened = await handle.stat({ bigint: true }); if (!opened.isFile()) throw new Error("unsafe detached entry"); const identity = await captureIdentity(path); if (identity.device !== opened.dev || identity.inode !== opened.ino || identity.mode !== Number(opened.mode)) throw new Error("detached entry identity changed"); const bytes = await handle.readFile(); const after = await handle.stat({ bigint: true }); if (!sameFileSnapshot(opened, after)) throw new Error("detached entry changed while reading"); await assertIdentity(path, identity); return { bytes, identity }; } finally { await handle.close(); }
}

export async function restoreEntrySnapshot(receipt: Receipt, expectedParentIdentity: PathIdentity, expectedLive: Buffer, desired: Buffer | undefined, onCheckpoint: ((checkpoint: TransactionCheckpoint) => void) | undefined): Promise<void> {
  const parent = dirname(receipt.entryPath); const detached = entryDetachPath(receipt); let snapshot = await optionalDetachedEntry(receipt);
  if (snapshot === undefined) { onCheckpoint?.("beforeRollbackEntryDetach"); onCheckpoint?.("afterRollbackEntryDetachReservation"); onCheckpoint?.("beforeRollbackEntryDetachMove"); await secureRenameNoReplace({ sourceDirectory: parent, sourceName: basename(receipt.entryPath), sourceDirectoryIdentity: expectedParentIdentity, destinationDirectory: parent, destinationName: basename(detached), destinationDirectoryIdentity: expectedParentIdentity, onDirectoriesBound: () => onCheckpoint?.("afterRollbackNativeDirectoriesBound") }); onCheckpoint?.("afterRollbackEntryDetach"); snapshot = await optionalDetachedEntry(receipt); }
  if (snapshot === undefined) throw new Error("detached entry is missing");
  try {
    if (!snapshot.bytes.equals(expectedLive)) throw new ConcurrentEntryChange("entry changed; stale rollback state");
    if (desired !== undefined && await optionalBytes(receipt.entryPath) === undefined) await secureCreateNoReplace({ directory: parent, name: basename(receipt.entryPath), directoryIdentity: expectedParentIdentity }, desired);
    if (!matchesSnapshot(await optionalBytes(receipt.entryPath), desired)) throw new ConcurrentEntryChange("entry changed; stale rollback state");
    onCheckpoint?.("beforeRollbackDetachFinalization"); await assertIdentity(detached, snapshot.identity);
  } catch (error) { try { if (await optionalBytes(receipt.entryPath) === undefined) await secureCreateNoReplace({ directory: parent, name: basename(receipt.entryPath), directoryIdentity: expectedParentIdentity }, snapshot.bytes); } catch { /* Preserve the primary failure and detached bytes without touching a substituted parent. */ } throw error; }
}

export async function restore(receipt: Receipt, request: TransactionRequest, bindingId: string, currentPath: string, receiptPath: string, bindingRoot: string, validateCopies = true, preserveEntry = false): Promise<void> {
  if (validateCopies) { const top = await requiredBytes(receiptPath, "transaction receipt"); const validated = await receiptWithMatchingBackup(top, request, bindingId); if (JSON.stringify(validated) !== JSON.stringify(receipt)) throw new Error("transaction receipt copies differ"); }
  const expectedBackupRootIdentity = loadIdentity(receipt.backupRootIdentity, "backup root")!; const expectedParentIdentity = loadIdentity(receipt.entryParentIdentity, "entry parent")!; const expectedInstallationIdentity = loadIdentity(receipt.installationIdentity, "installation")!; const expectedBindingRootIdentity = loadIdentity(receipt.bindingRootIdentity, "binding root")!; const expectedReleasesRootIdentity = loadIdentity(receipt.releasesRootIdentity, "releases root")!; const expectedReleaseIdentity = loadIdentity(receipt.releaseIdentity, "release"); const expectedLocalRulesParentIdentity = loadIdentity(receipt.localRulesParentIdentity, "local rules parent");
  await assertIdentity(receipt.backupRoot, expectedBackupRootIdentity); await assertIdentity(request.installationRoot, expectedInstallationIdentity); await assertIdentity(bindingRoot, expectedBindingRootIdentity); await assertIdentity(join(request.installationRoot, "releases"), expectedReleasesRootIdentity); await assertIdentity(dirname(receipt.entryPath), expectedParentIdentity); if (await exists(receipt.releasePath) && expectedReleaseIdentity !== undefined) await assertIdentity(receipt.releasePath, expectedReleaseIdentity); if (receipt.localRulesPath !== null && await exists(dirname(receipt.localRulesPath)) && expectedLocalRulesParentIdentity !== undefined) await assertIdentity(dirname(receipt.localRulesPath), expectedLocalRulesParentIdentity);
  const entryBefore = receipt.entryBackupDigest === null ? undefined : await verifiedBackup(receipt, request, "entry.bin", receipt.entryBackupDigest); const entryApplied = await verifiedBackup(receipt, request, "entry.applied.bin", receipt.entryAppliedDigest); const currentBefore = receipt.currentBackupDigest === null ? undefined : await verifiedBackup(receipt, request, "current.json", receipt.currentBackupDigest); const currentApplied = receipt.currentAppliedDigest === null ? undefined : await verifiedBackup(receipt, request, "current.applied.json", receipt.currentAppliedDigest); const localBefore = receipt.localRulesBackupDigest === null ? undefined : await verifiedBackup(receipt, request, "local-rules.bin", receipt.localRulesBackupDigest); const localApplied = receipt.localRulesAppliedDigest === null ? undefined : await verifiedBackup(receipt, request, "local-rules.applied.bin", receipt.localRulesAppliedDigest); const shared = await otherBindingReferences(receipt.releasePath, request.installationRoot, bindingId); const liveEntry = await optionalBytes(receipt.entryPath); const detachedEntry = (await optionalDetachedEntry(receipt))?.bytes; const liveCurrent = await optionalBytes(currentPath);
  if (!preserveEntry && (!matchesSnapshot(liveEntry, entryApplied) && !matchesSnapshot(liveEntry, entryBefore) && !(liveEntry === undefined && detachedEntry !== undefined) || detachedEntry !== undefined && !matchesSnapshot(detachedEntry, entryApplied) && !matchesSnapshot(detachedEntry, entryBefore) || detachedEntry !== undefined && liveEntry !== undefined && !matchesSnapshot(liveEntry, entryBefore) && !matchesSnapshot(liveEntry, detachedEntry))) throw new Error("entry changed; stale rollback state"); if (!matchesSnapshot(liveCurrent, currentApplied) && !matchesSnapshot(liveCurrent, currentBefore)) throw new Error("current metadata changed; stale rollback state");
  let liveLocal: Buffer | undefined; if (!shared && receipt.localRulesPath !== null) { liveLocal = await optionalBytes(receipt.localRulesPath); if (!matchesSnapshot(liveLocal, localApplied) && !matchesSnapshot(liveLocal, localBefore)) throw new Error("local rules changed; stale shared state"); }
  if (!shared && !receipt.releaseExisted && await exists(receipt.releasePath)) { const verified = await verifyRelease(receipt.releasePath); if (verified.version !== basename(receipt.releasePath)) throw new Error("installed release version does not match its directory"); }
  request.onCheckpoint?.("beforeRollbackEntry"); const entryNow = await optionalBytes(receipt.entryPath); const detachedNow = (await optionalDetachedEntry(receipt))?.bytes; if (!preserveEntry && (!matchesSnapshot(entryNow, entryApplied) && !matchesSnapshot(entryNow, entryBefore) && !(entryNow === undefined && detachedNow !== undefined) || detachedNow !== undefined && !matchesSnapshot(detachedNow, entryApplied) && !matchesSnapshot(detachedNow, entryBefore) || detachedNow !== undefined && entryNow !== undefined && !matchesSnapshot(entryNow, entryBefore) && !matchesSnapshot(entryNow, detachedNow))) throw new Error("entry changed; stale rollback state"); if (!preserveEntry && (detachedNow !== undefined || !matchesSnapshot(entryNow, entryBefore))) { request.onCheckpoint?.("afterRollbackEntryValidation"); const expectedLive = detachedNow ?? entryNow; if (expectedLive === undefined) throw new Error("entry changed; stale rollback state"); await restoreEntrySnapshot(receipt, expectedParentIdentity, expectedLive, entryBefore, request.onCheckpoint); } if (!preserveEntry && !matchesSnapshot(await optionalBytes(receipt.entryPath), entryBefore)) throw new Error("entry restore postimage changed"); request.onCheckpoint?.("afterRollbackEntry");
  await assertIdentity(bindingRoot, expectedBindingRootIdentity); const currentNow = await optionalBytes(currentPath); if (!matchesSnapshot(currentNow, currentApplied) && !matchesSnapshot(currentNow, currentBefore)) throw new Error("current metadata changed; stale rollback state"); if (!matchesSnapshot(currentNow, currentBefore)) { if (currentBefore !== undefined) { if (currentNow === undefined) await atomicCreate(currentPath, currentBefore, expectedBindingRootIdentity); else await atomicWrite(currentPath, currentBefore, expectedBindingRootIdentity, currentNow); } else await atomicRemove(currentPath, expectedBindingRootIdentity, currentNow!); } if (!matchesSnapshot(await optionalBytes(currentPath), currentBefore)) throw new Error("current metadata restore postimage changed"); request.onCheckpoint?.("afterRollbackCurrent"); if (!matchesSnapshot(await optionalBytes(currentPath), currentBefore) || !preserveEntry && !matchesSnapshot(await optionalBytes(receipt.entryPath), entryBefore)) throw new Error("restore joint postimage changed");
  if (!shared && receipt.localRulesPath !== null) { if (expectedLocalRulesParentIdentity === undefined) throw new Error("local rules parent identity is missing"); const localNow = await optionalBytes(receipt.localRulesPath); if (!matchesSnapshot(localNow, localApplied) && !matchesSnapshot(localNow, localBefore)) throw new Error("local rules changed; stale shared state"); if (receipt.releaseExisted && !matchesSnapshot(localNow, localBefore)) { if (localBefore !== undefined) { if (localNow === undefined) await atomicCreate(receipt.localRulesPath, localBefore, expectedLocalRulesParentIdentity); else await atomicWrite(receipt.localRulesPath, localBefore, expectedLocalRulesParentIdentity, localNow); } else await atomicRemove(receipt.localRulesPath, expectedLocalRulesParentIdentity, localNow!); } if (receipt.releaseExisted && !matchesSnapshot(await optionalBytes(receipt.localRulesPath), localBefore)) throw new Error("local rules restore postimage changed"); }
  if (!shared && !receipt.releaseExisted && await exists(receipt.releasePath)) { if (expectedReleaseIdentity === undefined) throw new Error("release identity is missing"); if (receipt.localRulesPath !== null) { const localNow = await optionalBytes(receipt.localRulesPath); if (!matchesSnapshot(localNow, localApplied) && !matchesSnapshot(localNow, localBefore)) throw new Error("local rules changed; stale shared state"); } const verified = await verifyRelease(receipt.releasePath); if (verified.version !== basename(receipt.releasePath)) throw new Error("installed release version does not match its directory"); await assertIdentity(receipt.releasePath, expectedReleaseIdentity); }
  const expectedFinalLocal = receipt.releaseExisted ? localBefore : localApplied; if (!preserveEntry && !matchesSnapshot(await optionalBytes(receipt.entryPath), entryBefore) || !matchesSnapshot(await optionalBytes(currentPath), currentBefore) || !shared && receipt.localRulesPath !== null && !matchesSnapshot(await optionalBytes(receipt.localRulesPath), expectedFinalLocal)) throw new Error("restore final joint postimage changed"); const rolled = Buffer.from(`${JSON.stringify({ ...receipt, status: "ROLLED_BACK" })}\n`); const backupReceiptBefore = await requiredBytes(join(receipt.backupRoot, "receipt.json"), "backup receipt"); await atomicWrite(join(receipt.backupRoot, "receipt.json"), rolled, expectedBackupRootIdentity, backupReceiptBefore); request.onCheckpoint?.("afterRollbackBackupReceipt"); const topReceiptBefore = await requiredBytes(receiptPath, "transaction receipt"); await atomicWrite(receiptPath, rolled, expectedBindingRootIdentity, topReceiptBefore);
}
