import { randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";
import { basename, dirname, join, relative } from "node:path";
import type { InstallResult, InstallerCommand, InstallPhase } from "./contracts.ts";
import { ConcurrentEntryChange, InstallerFailure, InterruptedFailure } from "./errors.ts";
import { assertIdentity, captureIdentity } from "./filesystem.ts";
import { installManagedBlock, removeManagedBlock, verifyManagedBlock } from "./managed-block.ts";
import { probeNativeFilesystemCapability, secureCreateDirectory } from "./native-filesystem.ts";
import { planInstallation } from "./planner.ts";
import { verifyRelease } from "./release.ts";
import { SignalCoordinator, SignalInterruption } from "./signals.ts";
import { inspectTarget } from "./target.ts";
import { architecture, type TransactionCheckpoint, type TransactionRequest } from "./installer/contracts.ts";
import { bindingIdFor, resolveContext, type Context } from "./installer/context.ts";
import { withInstallationLock } from "./installer/locking.ts";
import { optionalCanonicalLocalRules, readCanonicalLocalRules, type LocalRulesMutation } from "./installer/local-rules.ts";
import { atomicCreate, atomicRemove, atomicWrite, ensureDirectoryTree } from "./installer/mutation.ts";
import { digest, exists, matchesSnapshot, optionalBytes } from "./installer/snapshot.ts";
import { receiptWithMatchingBackup, storeIdentity, type Receipt } from "./installer/receipts.ts";
import { restore } from "./installer/recovery.ts";
import { activateRelease, prepareRelease } from "./installer/release-staging.ts";

export type { TransactionCheckpoint, TransactionRequest } from "./installer/contracts.ts";

export class InstallerTransaction {
  private readonly request: TransactionRequest;
  constructor(request: TransactionRequest) { this.request = request; }
  private bindingId(): string { return bindingIdFor(this.request.targetRoot, this.request.entryFile); }
  private bindingRoot(): string { return join(this.request.installationRoot, "bindings", this.bindingId()); }
  private currentPath(): string { return join(this.bindingRoot(), "current.json"); }
  private receiptPath(): string { return join(this.bindingRoot(), "last-transaction.json"); }
  private fault(phase: InstallPhase): void { if (this.request.faultAfter === phase) throw new Error(`injected failure after ${phase}`); }
  private result(command: InstallerCommand, state: InstallResult["state"], phase: InstallPhase, rollbackStatus: InstallResult["rollbackStatus"], plan?: InstallResult["plan"]): InstallResult { const capabilities: InstallResult["capabilities"][number][] = []; if (["CURRENT", "OUTDATED", "DOWNGRADE_BLOCKED"].includes(state)) capabilities.push("FILESYSTEM_INSTALLED", "BINDING_MATERIALIZED", "DIGEST_VERIFIED", "ROLLBACK_AVAILABLE"); return { schemaVersion: 1, architecture, command, outcome: "SUCCESS", state, phase, rollbackStatus, capabilities, ...(plan === undefined ? {} : { plan }) }; }
  async inspect(command: "inspect" | "status" = "inspect"): Promise<InstallResult> { const context = await resolveContext(this.request, this.bindingId(), this.currentPath(), this.receiptPath()); return this.result(command, context.state, "inspect", ["CURRENT", "OUTDATED", "DOWNGRADE_BLOCKED"].includes(context.state) ? "AVAILABLE" : "NOT_REQUIRED"); }
  async status(): Promise<InstallResult> { return this.inspect("status"); }
  async localVersion(): Promise<string | undefined> { const context = await resolveContext(this.request, this.bindingId(), this.currentPath(), this.receiptPath()); return context.current?.version; }
  async plan(command: InstallerCommand = "plan"): Promise<InstallResult> { const context = await resolveContext(this.request, this.bindingId(), this.currentPath(), this.receiptPath()); const planned = command === "plan" ? "install" : command; const localRulesOperation = ["install", "update", "uninstall"].includes(planned) ? await this.plannedLocalRulesOperation(planned as "install" | "update" | "uninstall", context) : undefined; const plan = planInstallation({ command: planned, state: context.state, entryPath: context.target.entryPath, installationRoot: this.request.installationRoot, version: context.release.version, ...(localRulesOperation === undefined ? {} : { localRulesOperation }), localRulesPath: context.release.localRulesPath, bindingId: this.bindingId() }); return this.result("plan", context.state, "plan", "NOT_REQUIRED", plan); }
  async verify(): Promise<InstallResult> { const context = await resolveContext(this.request, this.bindingId(), this.currentPath(), this.receiptPath()); if (context.state !== "CURRENT") throw new Error(`verification failed: ${context.state}`); return this.result("verify", "CURRENT", "verify", "AVAILABLE"); }
  async install(): Promise<InstallResult> { return this.mutate("install"); }
  async update(): Promise<InstallResult> { return this.mutate("update"); }
  async uninstall(): Promise<InstallResult> { return this.mutate("uninstall"); }
  private async plannedLocalRulesOperation(operation: "install" | "update" | "uninstall", context: Context): Promise<"create" | "replace" | undefined> {
    if (operation === "uninstall") return undefined;
    const target = join(this.request.installationRoot, "releases", context.release.version, "bundle", "agent-governance", context.release.localRulesPath);
    const targetExists = await optionalCanonicalLocalRules(target) !== undefined;
    if (this.request.localRules !== undefined) return targetExists ? "replace" : "create";
    if (operation !== "update" || context.current === undefined || context.current.version === context.release.version || context.installedLocalRules === undefined || targetExists) return undefined;
    return "create";
  }
  private async mutate(operation: "install" | "update" | "uninstall"): Promise<InstallResult> {
    const coordinator = new SignalCoordinator(this.request.signalSource); coordinator.start();
    try {
      const context = await resolveContext(this.request, this.bindingId(), this.currentPath(), this.receiptPath()); if (["TAMPERED", "RECOVERY_REQUIRED", "DOWNGRADE_BLOCKED"].includes(context.state)) throw new Error(`unsafe install state: ${context.state}`); if (operation === "install" && context.state === "OUTDATED") throw new Error("unsafe install state: OUTDATED; use update"); if (operation === "update" && !["OUTDATED", "CURRENT"].includes(context.state)) throw new Error(`unsafe update state: ${context.state}; update requires OUTDATED`);
      const localRulesOperation = await this.plannedLocalRulesOperation(operation, context);
      const plan = planInstallation({ command: operation, state: context.state, entryPath: context.target.entryPath, installationRoot: this.request.installationRoot, version: context.release.version, ...(localRulesOperation === undefined ? {} : { localRulesOperation }), localRulesPath: context.release.localRulesPath, bindingId: this.bindingId() });
      if (this.request.dryRun) return this.result(operation, context.state, "plan", "NOT_REQUIRED", plan); if (operation === "install" && context.state === "CURRENT") return this.result(operation, "CURRENT", "verify", "AVAILABLE", plan); if (operation === "update" && context.state === "CURRENT" && this.request.localRules === undefined) return this.result(operation, "CURRENT", "verify", "AVAILABLE", plan); if (operation === "uninstall" && (context.state === "ABSENT" || context.state === "FRESH")) return this.result(operation, "ABSENT", "verify", "NOT_REQUIRED", plan);
      coordinator.checkpoint("plan"); await probeNativeFilesystemCapability(dirname(context.target.entryPath), context.target.entryParentIdentity); if (context.target.installationAncestorPath !== dirname(context.target.entryPath)) await probeNativeFilesystemCapability(context.target.installationAncestorPath, context.target.installationAncestorIdentity); this.request.onCheckpoint?.("beforeMutation"); coordinator.checkpoint("plan"); await withInstallationLock(this.request.installationRoot, context.target.installationAncestorPath, context.target.installationAncestorIdentity, () => this.performMutation(operation, context, coordinator)); return this.result(operation, operation === "uninstall" ? "ABSENT" : "CURRENT", "verify", "AVAILABLE", plan);
    } catch (error) { if (error instanceof SignalInterruption) throw new InterruptedFailure(error.signal, error.phase, "NOT_REQUIRED"); throw error; } finally { coordinator.dispose(); }
  }
  private async localRulesMutation(context: Context): Promise<LocalRulesMutation | undefined> {
    const releasePath = join(this.request.installationRoot, "releases", context.release.version); const targetPath = join(releasePath, "bundle", "agent-governance", context.release.localRulesPath); const previous = await optionalCanonicalLocalRules(targetPath); let source: Buffer | undefined;
    if (this.request.localRules !== undefined) source = await readCanonicalLocalRules(this.request.localRules, () => this.request.onCheckpoint?.("afterLocalRulesSourceOpen"));
    else if (context.current !== undefined && context.current.version !== context.release.version) { if (previous !== undefined) return undefined; const installed = await verifyRelease(join(this.request.installationRoot, "releases", context.current.version)); const liveSource = await optionalCanonicalLocalRules(join(this.request.installationRoot, "releases", context.current.version, "bundle", "agent-governance", installed.localRulesPath)); if (!matchesSnapshot(liveSource, context.installedLocalRules)) throw new Error("local rules changed since inspection"); source = liveSource; }
    if (source === undefined) return undefined; return { targetPath, source, ...(previous === undefined ? {} : { previous }) };
  }
  private async performMutation(operation: "install" | "update" | "uninstall", context: Context, coordinator: SignalCoordinator): Promise<void> {
    const root = this.request.installationRoot; const bindingId = this.bindingId(); const id = randomUUID(); const backupRoot = join(root, "backups", bindingId, id); const currentPath = this.currentPath(); const receiptPath = this.receiptPath(); const releasePath = join(root, "releases", context.release.version); const releaseExisted = await exists(releasePath); const localRules = operation === "uninstall" ? undefined : await this.localRulesMutation(context);
    const installationIdentity = await captureIdentity(root); const backupsIdentity = await ensureDirectoryTree(root, installationIdentity, join(root, "backups")); const bindingBackupsIdentity = await ensureDirectoryTree(join(root, "backups"), backupsIdentity, join(root, "backups", bindingId)); const releasesRootIdentity = await ensureDirectoryTree(root, installationIdentity, join(root, "releases")); const bindingsIdentity = await ensureDirectoryTree(root, installationIdentity, join(root, "bindings")); const bindingRootIdentity = await ensureDirectoryTree(join(root, "bindings"), bindingsIdentity, this.bindingRoot()); await secureCreateDirectory({ directory: join(root, "backups", bindingId), name: basename(backupRoot), directoryIdentity: bindingBackupsIdentity }); const backupRootIdentity = await captureIdentity(backupRoot);
    const current = await optionalBytes(currentPath); const appliedEntry = operation === "uninstall" ? removeManagedBlock(context.entry) : installManagedBlock(context.entry, context.binding); const appliedCurrent = operation === "uninstall" ? undefined : Buffer.from(`${JSON.stringify({ schemaVersion: 1, ...context.binding, targetRoot: this.request.targetRoot, entryFile: this.request.entryFile }, null, 2)}\n`); if (context.target.entryExists) await atomicCreate(join(backupRoot, "entry.bin"), context.entry, backupRootIdentity); else await atomicCreate(join(backupRoot, "entry.absent"), "absent\n", backupRootIdentity); if (current !== undefined) await atomicCreate(join(backupRoot, "current.json"), current, backupRootIdentity); else await atomicCreate(join(backupRoot, "current.absent"), "absent\n", backupRootIdentity); await atomicCreate(join(backupRoot, "entry.applied.bin"), appliedEntry, backupRootIdentity); if (appliedCurrent !== undefined) await atomicCreate(join(backupRoot, "current.applied.json"), appliedCurrent, backupRootIdentity); else await atomicCreate(join(backupRoot, "current.applied.absent"), "absent\n", backupRootIdentity);
    if (localRules !== undefined) { await atomicCreate(join(backupRoot, "local-rules.applied.bin"), localRules.source, backupRootIdentity); if (localRules.previous !== undefined) await atomicCreate(join(backupRoot, "local-rules.bin"), localRules.previous, backupRootIdentity); this.request.onCheckpoint?.("afterLocalRulesBackup"); }
    this.request.onCheckpoint?.("afterBackupWrites");
    if (context.target.entryExists ? !(await readFile(join(backupRoot, "entry.bin"))).equals(context.entry) : await readFile(join(backupRoot, "entry.absent"), "utf8") !== "absent\n") throw new Error("backup readback failed"); if (current !== undefined ? !(await readFile(join(backupRoot, "current.json"))).equals(current) : await readFile(join(backupRoot, "current.absent"), "utf8") !== "absent\n") throw new Error("backup readback failed"); if (!(await readFile(join(backupRoot, "entry.applied.bin"))).equals(appliedEntry) || (appliedCurrent !== undefined ? !(await readFile(join(backupRoot, "current.applied.json"))).equals(appliedCurrent) : await readFile(join(backupRoot, "current.applied.absent"), "utf8") !== "absent\n")) throw new Error("backup readback failed"); if (localRules !== undefined && !(await readFile(join(backupRoot, "local-rules.applied.bin"))).equals(localRules.source)) throw new Error("backup readback failed"); if (localRules?.previous !== undefined && !(await readFile(join(backupRoot, "local-rules.bin"))).equals(localRules.previous)) throw new Error("backup readback failed");
    const preparedRelease = await prepareRelease(context.release, backupRoot, backupRootIdentity, operation, this.request); const preparedReleaseRoot = preparedRelease.stage ?? preparedRelease.destination; const localRulesParentIdentity = localRules === undefined ? undefined : await captureIdentity(join(preparedReleaseRoot, relative(releasePath, dirname(localRules.targetPath))));
    const receipt: Receipt = { schemaVersion: 1, id, bindingId, status: "PREPARED", operation, backupRoot, backupRootIdentity: storeIdentity(backupRootIdentity), entryPath: context.target.entryPath, entryParentIdentity: storeIdentity(context.target.entryParentIdentity), installationIdentity: storeIdentity(installationIdentity), bindingRootIdentity: storeIdentity(bindingRootIdentity), releasesRootIdentity: storeIdentity(releasesRootIdentity), releaseIdentity: preparedRelease.identity === undefined ? null : storeIdentity(preparedRelease.identity), entryExisted: context.target.entryExists, currentExisted: current !== undefined, releasePath, releaseExisted, localRulesPath: localRules?.targetPath ?? null, localRulesParentIdentity: localRulesParentIdentity === undefined ? null : storeIdentity(localRulesParentIdentity), localRulesExisted: localRules?.previous !== undefined, entryBackupDigest: context.target.entryExists ? digest(context.entry) : null, currentBackupDigest: current === undefined ? null : digest(current), localRulesBackupDigest: localRules?.previous === undefined ? null : digest(localRules.previous), entryAppliedDigest: digest(appliedEntry), currentAppliedDigest: appliedCurrent === undefined ? null : digest(appliedCurrent), localRulesAppliedDigest: localRules === undefined ? null : digest(localRules.source) }; const prepared = Buffer.from(`${JSON.stringify(receipt)}\n`); await atomicCreate(join(backupRoot, "receipt.json"), prepared, backupRootIdentity); const previousReceipt = await optionalBytes(receiptPath); if (previousReceipt === undefined) await atomicCreate(receiptPath, prepared, bindingRootIdentity); else await atomicWrite(receiptPath, prepared, bindingRootIdentity, previousReceipt);
    this.request.onCheckpoint?.("afterReceipt"); await assertIdentity(root, installationIdentity);
    try { const liveEntry = await optionalBytes(context.target.entryPath); if (context.target.entryExists ? liveEntry === undefined || !liveEntry.equals(context.entry) : liveEntry !== undefined) throw new ConcurrentEntryChange("entry changed: identity changed, content changed, or no longer absent"); if (context.target.entryIdentity !== undefined) await assertIdentity(context.target.entryPath, context.target.entryIdentity); if (!matchesSnapshot(await optionalBytes(currentPath), current)) throw new Error("current metadata changed after backup"); if (localRules !== undefined && !matchesSnapshot(await optionalBytes(localRules.targetPath), localRules.previous)) throw new Error("local rules changed after backup"); } catch (error) { const rolled = Buffer.from(`${JSON.stringify({ ...receipt, status: "ROLLED_BACK" })}\n`); await atomicWrite(join(backupRoot, "receipt.json"), rolled, backupRootIdentity, prepared); await atomicWrite(receiptPath, rolled, bindingRootIdentity, prepared); throw error; }
    let verifiedLocalRules: Buffer | undefined;
    try {
      coordinator.checkpoint("backup"); this.fault("backup"); await assertIdentity(this.request.targetRoot, context.target.targetIdentity); await assertIdentity(dirname(context.target.entryPath), context.target.entryParentIdentity);
      if (operation === "uninstall") { await atomicWrite(context.target.entryPath, appliedEntry, context.target.entryParentIdentity, context.entry); await atomicRemove(currentPath, bindingRootIdentity, current!); }
      else { if (localRules !== undefined) await assertIdentity(join(preparedReleaseRoot, relative(releasePath, dirname(localRules.targetPath))), localRulesParentIdentity!); await activateRelease(preparedRelease, backupRootIdentity, releasesRootIdentity); if (localRules !== undefined) { if (localRules.previous === undefined) await atomicCreate(localRules.targetPath, localRules.source, localRulesParentIdentity!); else await atomicWrite(localRules.targetPath, localRules.source, localRulesParentIdentity!, localRules.previous); } this.fault("stage"); if (current === undefined) await atomicCreate(currentPath, appliedCurrent!, bindingRootIdentity); else await atomicWrite(currentPath, appliedCurrent!, bindingRootIdentity, current); this.request.onCheckpoint?.("afterCurrent"); coordinator.checkpoint("activate"); if (!matchesSnapshot(await optionalBytes(currentPath), appliedCurrent)) throw new Error("current metadata postimage changed"); if (localRules !== undefined && !matchesSnapshot(await optionalBytes(localRules.targetPath), localRules.source)) throw new Error("local rules postimage changed"); const lateEntry = await optionalBytes(context.target.entryPath); if (context.target.entryExists ? lateEntry === undefined || !lateEntry.equals(context.entry) : lateEntry !== undefined) throw new ConcurrentEntryChange("entry changed before activation"); if (context.target.entryExists) await atomicWrite(context.target.entryPath, appliedEntry, context.target.entryParentIdentity, context.entry); else await atomicCreate(context.target.entryPath, appliedEntry, context.target.entryParentIdentity); }
      this.request.onCheckpoint?.("afterEntry"); coordinator.checkpoint("activate"); this.fault("activate"); this.request.onCheckpoint?.("beforeVerification"); coordinator.checkpoint("verify"); if (!matchesSnapshot(await optionalBytes(context.target.entryPath), appliedEntry)) throw new Error("entry postimage changed"); if (!matchesSnapshot(await optionalBytes(currentPath), appliedCurrent)) throw new Error("current metadata postimage changed"); if (localRules !== undefined && !matchesSnapshot(await optionalBytes(localRules.targetPath), localRules.source)) throw new Error("local rules postimage changed"); if (operation === "uninstall") { const bytes = await readFile(context.target.entryPath); if (!removeManagedBlock(bytes).equals(bytes)) throw new Error("managed block remains after uninstall"); } else { verifyManagedBlock(await readFile(context.target.entryPath), context.binding); await verifyRelease(releasePath); verifiedLocalRules = await optionalCanonicalLocalRules(join(releasePath, "bundle", "agent-governance", context.release.localRulesPath)); } coordinator.checkpoint("verify"); this.fault("verify"); const committed = Buffer.from(`${JSON.stringify({ ...receipt, status: "COMMITTED" })}\n`); await atomicWrite(receiptPath, committed, bindingRootIdentity, prepared); this.request.onCheckpoint?.("afterCommitTopReceipt"); await atomicWrite(join(backupRoot, "receipt.json"), committed, backupRootIdentity, prepared); try { if (!matchesSnapshot(await optionalBytes(context.target.entryPath), appliedEntry) || !matchesSnapshot(await optionalBytes(currentPath), appliedCurrent) || operation !== "uninstall" && !matchesSnapshot(await optionalCanonicalLocalRules(join(releasePath, "bundle", "agent-governance", context.release.localRulesPath)), verifiedLocalRules)) throw new Error("final commit joint postimage changed"); } catch (error) { await atomicWrite(join(backupRoot, "receipt.json"), prepared, backupRootIdentity, committed); await atomicWrite(receiptPath, prepared, bindingRootIdentity, committed); throw error; }
    } catch (error) {
      try { this.request.onCheckpoint?.("duringRollback"); if (this.request.faultDuringRollback) throw new Error("injected rollback failure"); await restore(receipt, this.request, this.bindingId(), this.currentPath(), this.receiptPath(), this.bindingRoot(), false, error instanceof ConcurrentEntryChange); } catch (rollbackError) { throw new InstallerFailure("ROLLBACK_FAILED", "rollback", "installation", "ROLLBACK_FAILED", `${(error as Error).message}; rollback failed: ${(rollbackError as Error).message}`, "FAILED"); }
      try { coordinator.checkpoint("rollback"); } catch (signal) { if (signal instanceof SignalInterruption) throw new InterruptedFailure(signal.signal, signal.phase, "SUCCEEDED"); throw signal; }
      if (error instanceof SignalInterruption) throw new InterruptedFailure(error.signal, error.phase, "SUCCEEDED"); throw new InstallerFailure("VERIFICATION_ROLLED_BACK", "verify", "installation", "VERIFICATION_ROLLED_BACK", (error as Error).message, "SUCCEEDED");
    }
  }
  async rollback(): Promise<InstallResult> { const coordinator = new SignalCoordinator(this.request.signalSource); let restoreVerified = false; coordinator.start(); try { const target = await inspectTarget(this.request.targetRoot, this.request.entryFile, this.request.installationRoot); const bytes = await optionalBytes(this.receiptPath()); if (bytes === undefined) throw new Error("rollback receipt is missing"); const receipt = await receiptWithMatchingBackup(bytes, this.request, this.bindingId()); coordinator.checkpoint("rollback"); if (this.request.dryRun) return this.result("rollback", "RECOVERY_REQUIRED", "plan", "AVAILABLE"); await probeNativeFilesystemCapability(dirname(target.entryPath), target.entryParentIdentity); if (target.installationAncestorPath !== dirname(target.entryPath)) await probeNativeFilesystemCapability(target.installationAncestorPath, target.installationAncestorIdentity); if (receipt.status !== "ROLLED_BACK") await withInstallationLock(this.request.installationRoot, target.installationAncestorPath, target.installationAncestorIdentity, async () => { await assertIdentity(target.targetRoot, target.targetIdentity); if (target.entryIdentity !== undefined) await assertIdentity(target.entryPath, target.entryIdentity); await restore(receipt, this.request, this.bindingId(), this.currentPath(), this.receiptPath(), this.bindingRoot()); }, true); const restored = await resolveContext(this.request, this.bindingId(), this.currentPath(), this.receiptPath()); if (["TAMPERED", "RECOVERY_REQUIRED"].includes(restored.state)) throw new Error(`rollback verification failed: ${restored.state}`); restoreVerified = true; coordinator.checkpoint("rollback"); return this.result("rollback", restored.state, "rollback", "SUCCEEDED"); } catch (error) { if (error instanceof SignalInterruption) throw new InterruptedFailure(error.signal, error.phase, restoreVerified ? "SUCCEEDED" : "NOT_REQUIRED"); throw error; } finally { coordinator.dispose(); } }
}
