import { createHash, randomUUID } from "node:crypto";
import { access, cp, link, lstat, mkdir, mkdtemp, open, readFile, realpath, readdir, rename, rm, rmdir, writeFile } from "node:fs/promises";
import { constants } from "node:fs";
import { basename, dirname, isAbsolute, join } from "node:path";
import type { InstallPhase, InstallResult, InstallerCommand, InstallerRequest } from "./contracts.ts";
import { InstallerFailure, InterruptedFailure } from "./errors.ts";
import { assertIdentity, captureIdentity, validateAllowedPath } from "./filesystem.ts";
import { installManagedBlock, removeManagedBlock, verifyManagedBlock, type GovernanceBinding } from "./managed-block.ts";
import { planInstallation } from "./planner.ts";
import { verifyRelease, type VerifiedRelease } from "./release.ts";
import { SignalCoordinator, SignalInterruption, type SignalSource } from "./signals.ts";
import { inspectTarget, type TargetInspection } from "./target.ts";

export type TransactionCheckpoint = "beforeMutation" | "afterLocalRulesSourceOpen" | "afterLocalRulesBackup" | "afterBackupWrites" | "afterReceipt" | "afterEntry" | "afterCurrent" | "beforeVerification" | "duringRollback" | "beforeRollbackEntry" | "afterRollbackEntry" | "afterRollbackCurrent" | "afterCommitTopReceipt" | "afterRollbackBackupReceipt";
export interface TransactionRequest extends InstallerRequest { readonly faultAfter?: InstallPhase; readonly faultDuringRollback?: boolean; readonly signalSource?: SignalSource; readonly onCheckpoint?: (checkpoint: TransactionCheckpoint) => void; }
interface CurrentMetadata extends GovernanceBinding { readonly schemaVersion: 1; readonly targetRoot: string; readonly entryFile: string; }
interface Receipt { readonly schemaVersion: 1; readonly id: string; readonly bindingId: string; readonly status: "PREPARED" | "COMMITTED" | "ROLLED_BACK"; readonly operation: "install" | "update" | "uninstall"; readonly backupRoot: string; readonly entryPath: string; readonly entryExisted: boolean; readonly currentExisted: boolean; readonly releasePath: string; readonly releaseExisted: boolean; readonly localRulesPath: string | null; readonly localRulesExisted: boolean; readonly entryBackupDigest: string | null; readonly currentBackupDigest: string | null; readonly localRulesBackupDigest: string | null; readonly entryAppliedDigest: string; readonly currentAppliedDigest: string | null; readonly localRulesAppliedDigest: string | null; }
interface LocalRulesMutation { readonly targetPath: string; readonly source: Buffer; readonly previous?: Buffer; }
interface Context { readonly target: TargetInspection; readonly release: VerifiedRelease; readonly binding: GovernanceBinding; readonly current?: CurrentMetadata; readonly installedLocalRules?: Buffer; readonly entry: Buffer; readonly state: InstallResult["state"]; }

class ConcurrentEntryChange extends Error {}

const architecture = "GLOBAL_EXPLICIT_PATH_MANAGED_BLOCK" as const;
const SEMVER = /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?$/;
const RECEIPT_KEYS = ["schemaVersion", "id", "bindingId", "status", "operation", "backupRoot", "entryPath", "entryExisted", "currentExisted", "releasePath", "releaseExisted", "localRulesPath", "localRulesExisted", "entryBackupDigest", "currentBackupDigest", "localRulesBackupDigest", "entryAppliedDigest", "currentAppliedDigest", "localRulesAppliedDigest"] as const;
const CURRENT_KEYS = ["schemaVersion", "version", "installationRoot", "governancePath", "manifestPath", "governanceDigest", "manifestDigest", "bundleDigest", "targetRoot", "entryFile"] as const;

async function exists(path: string): Promise<boolean> { try { await access(path); return true; } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return false; throw error; } }
async function optionalBytes(path: string): Promise<Buffer | undefined> { try { const stat = await lstat(path); if (stat.isSymbolicLink() || !stat.isFile()) throw new Error(`unsafe regular file: ${path}`); return await readFile(path); } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return undefined; throw error; } }
async function requiredBytes(path: string, label: string): Promise<Buffer> { const value = await optionalBytes(path); if (value === undefined) throw new Error(`${label} is missing`); return value; }
async function ensureSafeDirectory(path: string, mode = 0o700): Promise<void> { try { await mkdir(path, { mode }); } catch (error) { if ((error as NodeJS.ErrnoException).code !== "EEXIST") throw error; } const stat = await lstat(path); if (stat.isSymbolicLink() || !stat.isDirectory() || await realpath(path) !== path) throw new Error(`unsafe symlink or non-canonical directory: ${path}`); }
async function atomicWrite(path: string, value: Buffer | string): Promise<void> { await mkdir(dirname(path), { recursive: true }); const temporary = `${path}.${randomUUID()}.tmp`; await writeFile(temporary, value, { mode: 0o600, flag: "wx" }); await rename(temporary, path); const expected = Buffer.isBuffer(value) ? value : Buffer.from(value); if (!(await readFile(path)).equals(expected)) throw new Error("atomic write readback failed"); }
async function atomicCreate(path: string, value: Buffer | string): Promise<void> { await mkdir(dirname(path), { recursive: true }); const temporary = `${path}.${randomUUID()}.tmp`; const expected = Buffer.isBuffer(value) ? value : Buffer.from(value); try { await writeFile(temporary, value, { mode: 0o600, flag: "wx" }); try { await link(temporary, path); } catch (error) { if ((error as NodeJS.ErrnoException).code === "EEXIST") throw new ConcurrentEntryChange("entry no longer absent"); throw error; } if (!(await readFile(path)).equals(expected)) throw new Error("atomic create readback failed"); } finally { await rm(temporary, { force: true }); } }
function digest(value: Buffer): string { return createHash("sha256").update(value).digest("hex"); }
function matchesSnapshot(live: Buffer | undefined, expected: Buffer | undefined): boolean { return live === undefined ? expected === undefined : expected !== undefined && live.equals(expected); }
function validateLocalRules(content: Buffer): void { let text: string; try { text = new TextDecoder("utf-8", { fatal: true }).decode(content); } catch { throw new Error("local rules contain invalid UTF-8 encoding"); } if (/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/.test(text)) throw new Error("local rules contain a raw control character"); }
function sameFileIdentity(left: { dev: bigint; ino: bigint }, right: { dev: bigint; ino: bigint }): boolean { return left.dev === right.dev && left.ino === right.ino; }
function sameFileSnapshot(left: { dev: bigint; ino: bigint; size: bigint; mtimeNs: bigint; ctimeNs: bigint }, right: { dev: bigint; ino: bigint; size: bigint; mtimeNs: bigint; ctimeNs: bigint }): boolean { return sameFileIdentity(left, right) && left.size === right.size && left.mtimeNs === right.mtimeNs && left.ctimeNs === right.ctimeNs; }
async function readCanonicalLocalRules(path: string, onOpen?: () => void): Promise<Buffer> { if (!isAbsolute(path) || !/\.md$/i.test(path)) throw new Error("local rules must be an absolute canonical Markdown file"); const before = await lstat(path, { bigint: true }); if (before.isSymbolicLink() || !before.isFile() || await realpath(path) !== path) throw new Error("local rules must be an absolute canonical regular non-symlink file"); const handle = await open(path, constants.O_RDONLY | constants.O_NOFOLLOW); try { const opened = await handle.stat({ bigint: true }); if (!opened.isFile() || !sameFileSnapshot(before, opened)) throw new Error("local rules source identity changed"); onOpen?.(); const liveBeforeRead = await lstat(path, { bigint: true }); if (liveBeforeRead.isSymbolicLink() || !liveBeforeRead.isFile() || !sameFileIdentity(opened, liveBeforeRead) || await realpath(path) !== path) throw new Error("local rules source identity changed"); const content = await handle.readFile(); const after = await handle.stat({ bigint: true }); const liveAfterRead = await lstat(path, { bigint: true }); if (!sameFileSnapshot(opened, after) || liveAfterRead.isSymbolicLink() || !liveAfterRead.isFile() || !sameFileIdentity(after, liveAfterRead) || await realpath(path) !== path) throw new Error("local rules source changed while reading"); validateLocalRules(content); return content; } finally { await handle.close(); } }
async function optionalCanonicalLocalRules(path: string): Promise<Buffer | undefined> { try { return await readCanonicalLocalRules(path); } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return undefined; throw error; } }
function parseObject<T>(bytes: Buffer, keys: readonly string[], label: string): T { let value: unknown; try { value = JSON.parse(bytes.toString("utf8")); } catch { throw new Error(`${label} is invalid JSON`); } if (typeof value !== "object" || value === null || Array.isArray(value) || Object.keys(value).sort().join("\0") !== [...keys].sort().join("\0")) throw new Error(`${label} has invalid schema`); return value as T; }
function bindingIdFor(targetRoot: string, entryFile: string): string { return createHash("sha256").update(targetRoot).update("\0").update(entryFile).digest("hex"); }
function compareSemver(left: string, right: string): number {
  const a = SEMVER.exec(left); const b = SEMVER.exec(right); if (a === null || b === null) throw new Error("invalid release version in current metadata");
  for (let index = 1; index <= 3; index += 1) { const difference = Number(a[index]) - Number(b[index]); if (difference !== 0) return Math.sign(difference); }
  const leftPre = a[4]; const rightPre = b[4]; if (leftPre === undefined) return rightPre === undefined ? 0 : 1; if (rightPre === undefined) return -1;
  const leftParts = leftPre.split("."); const rightParts = rightPre.split(".");
  for (let index = 0; index < Math.max(leftParts.length, rightParts.length); index += 1) { const x = leftParts[index]; const y = rightParts[index]; if (x === undefined) return -1; if (y === undefined) return 1; if (x === y) continue; const xn = /^\d+$/.test(x); const yn = /^\d+$/.test(y); if (xn && yn) return Number(x) < Number(y) ? -1 : 1; if (xn !== yn) return xn ? -1 : 1; return x < y ? -1 : 1; }
  return 0;
}

export class InstallerTransaction {
  private readonly request: TransactionRequest;
  constructor(request: TransactionRequest) { this.request = request; }
  private bindingId(): string { return bindingIdFor(this.request.targetRoot, this.request.entryFile); }
  private bindingRoot(): string { return join(this.request.installationRoot, "bindings", this.bindingId()); }
  private currentPath(): string { return join(this.bindingRoot(), "current.json"); }
  private receiptPath(): string { return join(this.bindingRoot(), "last-transaction.json"); }
  private processAlive(pid: number): boolean { try { process.kill(pid, 0); return true; } catch (error) { if ((error as NodeJS.ErrnoException).code === "ESRCH") return false; return true; } }
  private async reclaimStaleLock(lockPath: string): Promise<void> { await validateAllowedPath(lockPath, this.request.installationRoot, "directory"); const names = await readdir(lockPath); if (names.length !== 1 || names[0] !== "owner.json") throw new Error("transaction lock has invalid recovery metadata"); const ownerBytes = await requiredBytes(join(lockPath, "owner.json"), "transaction lock owner"); const owner = parseObject<{ schemaVersion: number; pid: number; token: string }>(ownerBytes, ["schemaVersion", "pid", "token"], "transaction lock owner"); if (owner.schemaVersion !== 1 || !Number.isSafeInteger(owner.pid) || owner.pid <= 0 || !/^[0-9a-f]{64}$/.test(owner.token)) throw new Error("transaction lock has invalid recovery metadata"); if (this.processAlive(owner.pid)) throw new Error("installation-root transaction lock is already active"); const identity = await captureIdentity(lockPath); const retired = join(this.request.installationRoot, `.transaction.lock.stale-${randomUUID()}`); await rename(lockPath, retired); await assertIdentity(retired, identity); if (!(await requiredBytes(join(retired, "owner.json"), "transaction lock owner")).equals(ownerBytes)) throw new Error("transaction lock ownership changed"); await rm(join(retired, "owner.json")); await rmdir(retired); }
  private async withInstallationLock<T>(ancestorPath: string, ancestorIdentity: Awaited<ReturnType<typeof captureIdentity>>, action: () => Promise<T>, allowStaleRecovery = false): Promise<T> { await assertIdentity(ancestorPath, ancestorIdentity); await mkdir(this.request.installationRoot, { recursive: true, mode: 0o700 }); await ensureSafeDirectory(this.request.installationRoot); const lockPath = join(this.request.installationRoot, ".transaction.lock"); try { await mkdir(lockPath, { mode: 0o700 }); } catch (error) { if ((error as NodeJS.ErrnoException).code !== "EEXIST") throw error; if (!allowStaleRecovery) throw new Error("installation-root transaction lock is already active"); await this.reclaimStaleLock(lockPath); await mkdir(lockPath, { mode: 0o700 }); } const owner = Buffer.from(`${JSON.stringify({ schemaVersion: 1, pid: process.pid, token: createHash("sha256").update(randomUUID()).digest("hex") })}\n`); await writeFile(join(lockPath, "owner.json"), owner, { flag: "wx", mode: 0o600 }); if (!(await readFile(join(lockPath, "owner.json"))).equals(owner)) throw new Error("transaction lock readback failed"); const lockIdentity = await captureIdentity(lockPath); const cleanup = async (): Promise<void> => { await assertIdentity(lockPath, lockIdentity); if (!(await requiredBytes(join(lockPath, "owner.json"), "transaction lock owner")).equals(owner)) throw new Error("transaction lock ownership changed"); await rm(join(lockPath, "owner.json")); await rmdir(lockPath); }; try { const result = await action(); await cleanup(); return result; } catch (error) { try { await cleanup(); } catch { /* Preserve the primary transaction failure and never remove an untrusted replacement. */ } throw error; } }
  private fault(phase: InstallPhase): void { if (this.request.faultAfter === phase) throw new Error(`injected failure after ${phase}`); }
  private result(command: InstallerCommand, state: InstallResult["state"], phase: InstallPhase, rollbackStatus: InstallResult["rollbackStatus"], plan?: InstallResult["plan"]): InstallResult { const capabilities: InstallResult["capabilities"][number][] = []; if (["CURRENT", "OUTDATED", "DOWNGRADE_BLOCKED"].includes(state)) capabilities.push("FILESYSTEM_INSTALLED", "BINDING_MATERIALIZED", "DIGEST_VERIFIED", "ROLLBACK_AVAILABLE"); return { schemaVersion: 1, architecture, command, outcome: "SUCCESS", state, phase, rollbackStatus, capabilities, ...(plan === undefined ? {} : { plan }) }; }
  private binding(release: VerifiedRelease): GovernanceBinding { const base = join(this.request.installationRoot, "releases", release.version, "bundle"); return { version: release.version, installationRoot: this.request.installationRoot, governancePath: join(base, "GOVERNANCE.md"), manifestPath: join(base, "agent-governance", "manifest.toml"), governanceDigest: release.governanceDigest, manifestDigest: release.manifestDigest, bundleDigest: release.bundleDigest }; }
  private parseCurrent(bytes: Buffer): CurrentMetadata { return parseObject<CurrentMetadata>(bytes, CURRENT_KEYS, "current metadata"); }
  private parseReceiptObject(bytes: Buffer): Receipt { return parseObject<Receipt>(bytes, RECEIPT_KEYS, "transaction receipt"); }
  private async validateReceipt(bytes: Buffer): Promise<Receipt> {
    const receipt = this.parseReceiptObject(bytes); const id = this.bindingId(); const backupBase = join(this.request.installationRoot, "backups", id); const releases = join(this.request.installationRoot, "releases");
    const digests = [receipt.entryBackupDigest, receipt.currentBackupDigest, receipt.localRulesBackupDigest, receipt.currentAppliedDigest, receipt.localRulesAppliedDigest];
    const scalar = typeof receipt.id === "string" && typeof receipt.bindingId === "string" && typeof receipt.backupRoot === "string" && typeof receipt.entryPath === "string" && typeof receipt.entryExisted === "boolean" && typeof receipt.currentExisted === "boolean" && typeof receipt.releasePath === "string" && typeof receipt.releaseExisted === "boolean" && typeof receipt.localRulesExisted === "boolean" && (receipt.localRulesPath === null || typeof receipt.localRulesPath === "string") && /^[0-9a-f]{64}$/.test(receipt.entryAppliedDigest) && digests.every((value) => value === null || typeof value === "string" && /^[0-9a-f]{64}$/.test(value));
    const expectedLocal = join(receipt.releasePath, "bundle", "agent-governance", (await verifyRelease(this.request.releaseRoot)).localRulesPath);
    if (!scalar || receipt.schemaVersion !== 1 || receipt.bindingId !== id || !/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(receipt.id) || !["PREPARED", "COMMITTED", "ROLLED_BACK"].includes(receipt.status) || !["install", "update", "uninstall"].includes(receipt.operation) || receipt.entryPath !== join(this.request.targetRoot, this.request.entryFile) || receipt.backupRoot !== join(backupBase, receipt.id) || dirname(receipt.releasePath) !== releases || !SEMVER.test(basename(receipt.releasePath)) || (receipt.localRulesPath !== null && receipt.localRulesPath !== expectedLocal) || (receipt.localRulesPath === null && receipt.localRulesExisted) || receipt.entryExisted !== (receipt.entryBackupDigest !== null) || receipt.currentExisted !== (receipt.currentBackupDigest !== null) || receipt.localRulesExisted !== (receipt.localRulesBackupDigest !== null) || (receipt.localRulesPath === null) !== (receipt.localRulesAppliedDigest === null) || (receipt.operation === "uninstall") !== (receipt.currentAppliedDigest === null)) throw new Error("transaction receipt has invalid values");
    return receipt;
  }
  private async receiptWithMatchingBackup(bytes: Buffer): Promise<Receipt> { const receipt = await this.validateReceipt(bytes); await validateAllowedPath(receipt.backupRoot, join(this.request.installationRoot, "backups", receipt.bindingId), "directory"); const backup = await requiredBytes(join(receipt.backupRoot, "receipt.json"), "backup receipt"); const backupReceipt = await this.validateReceipt(backup); const immutableMatch = RECEIPT_KEYS.every((key) => key === "status" || receipt[key] === backupReceipt[key]); const recoverableSplit = receipt.status === "COMMITTED" && ["PREPARED", "ROLLED_BACK"].includes(backupReceipt.status) || receipt.status === "PREPARED" && backupReceipt.status === "ROLLED_BACK"; if (!immutableMatch || (receipt.status === backupReceipt.status ? !bytes.equals(backup) : !recoverableSplit)) throw new Error("transaction receipt copies differ"); await this.validateBackupEvidence(receipt); return receipt; }
  private async context(): Promise<Context> {
    const target = await inspectTarget(this.request.targetRoot, this.request.entryFile, this.request.installationRoot); const release = await verifyRelease(this.request.releaseRoot); const binding = this.binding(release); const entry = (await optionalBytes(target.entryPath)) ?? Buffer.alloc(0); const currentBytes = await optionalBytes(this.currentPath()); const receiptBytes = await optionalBytes(this.receiptPath());
    if (receiptBytes !== undefined) { try { const receipt = await this.receiptWithMatchingBackup(receiptBytes); const backupReceipt = await requiredBytes(join(receipt.backupRoot, "receipt.json"), "backup receipt"); if (receipt.status === "PREPARED" || !receiptBytes.equals(backupReceipt)) return { target, release, binding, entry, state: "RECOVERY_REQUIRED" }; } catch { return { target, release, binding, entry, state: "TAMPERED" }; } }
    if (currentBytes !== undefined && receiptBytes === undefined) return { target, release, binding, entry, state: "TAMPERED" };
    if (currentBytes === undefined) { const hasMarker = entry.includes(Buffer.from("AGENT_GOVERNANCE_MANAGED_")); return { target, release, binding, entry, state: hasMarker ? "TAMPERED" : target.entryExists ? "FRESH" : "ABSENT" }; }
    let current: CurrentMetadata; try { current = this.parseCurrent(currentBytes); } catch { return { target, release, binding, entry, state: "TAMPERED" }; }
    try {
      if (current.schemaVersion !== 1 || current.installationRoot !== this.request.installationRoot || current.targetRoot !== this.request.targetRoot || current.entryFile !== this.request.entryFile || !SEMVER.test(current.version)) throw new Error("current metadata mismatch");
      const installed = await verifyRelease(join(this.request.installationRoot, "releases", current.version)); const installedLocalRules = await optionalCanonicalLocalRules(join(this.request.installationRoot, "releases", current.version, "bundle", "agent-governance", installed.localRulesPath)); const installedBinding = this.binding(installed); const expected: CurrentMetadata = { schemaVersion: 1, ...installedBinding, targetRoot: this.request.targetRoot, entryFile: this.request.entryFile };
      for (const key of Object.keys(expected) as (keyof CurrentMetadata)[]) if (current[key] !== expected[key]) throw new Error("current metadata mismatch");
      verifyManagedBlock(entry, installedBinding); const comparison = compareSemver(release.version, installed.version); if (comparison === 0 && release.bundleDigest !== installed.bundleDigest) throw new Error("release content changed without a version change");
      return { target, release, binding, current, ...(installedLocalRules === undefined ? {} : { installedLocalRules }), entry, state: comparison === 0 ? "CURRENT" : comparison > 0 ? "OUTDATED" : "DOWNGRADE_BLOCKED" };
    } catch { return { target, release, binding, current, entry, state: "TAMPERED" }; }
  }
  async inspect(command: "inspect" | "status" = "inspect"): Promise<InstallResult> { const context = await this.context(); return this.result(command, context.state, "inspect", ["CURRENT", "OUTDATED", "DOWNGRADE_BLOCKED"].includes(context.state) ? "AVAILABLE" : "NOT_REQUIRED"); }
  async status(): Promise<InstallResult> { return this.inspect("status"); }
  async plan(command: InstallerCommand = "plan"): Promise<InstallResult> { const context = await this.context(); const planned = command === "plan" ? "install" : command; const plan = planInstallation({ command: planned, state: context.state, entryPath: context.target.entryPath, installationRoot: this.request.installationRoot, version: context.release.version, localRules: this.request.localRules !== undefined, localRulesPath: context.release.localRulesPath, bindingId: this.bindingId() }); return this.result("plan", context.state, "plan", "NOT_REQUIRED", plan); }
  async verify(): Promise<InstallResult> { const context = await this.context(); if (context.state !== "CURRENT") throw new Error(`verification failed: ${context.state}`); return this.result("verify", "CURRENT", "verify", "AVAILABLE"); }
  async install(): Promise<InstallResult> { return this.mutate("install"); }
  async update(): Promise<InstallResult> { return this.mutate("update"); }
  async uninstall(): Promise<InstallResult> { return this.mutate("uninstall"); }
  private async mutate(operation: "install" | "update" | "uninstall"): Promise<InstallResult> {
    const coordinator = new SignalCoordinator(this.request.signalSource); coordinator.start();
    try {
      const context = await this.context(); if (["TAMPERED", "RECOVERY_REQUIRED", "DOWNGRADE_BLOCKED"].includes(context.state)) throw new Error(`unsafe install state: ${context.state}`); if (operation === "install" && context.state === "OUTDATED") throw new Error("unsafe install state: OUTDATED; use update"); if (operation === "update" && !["OUTDATED", "CURRENT"].includes(context.state)) throw new Error(`unsafe update state: ${context.state}; update requires OUTDATED`);
      const plan = planInstallation({ command: operation, state: context.state, entryPath: context.target.entryPath, installationRoot: this.request.installationRoot, version: context.release.version, localRules: this.request.localRules !== undefined, localRulesPath: context.release.localRulesPath, bindingId: this.bindingId() });
      if (this.request.dryRun) return this.result(operation, context.state, "plan", "NOT_REQUIRED", plan); if (operation === "install" && context.state === "CURRENT") return this.result(operation, "CURRENT", "verify", "AVAILABLE", plan); if (operation === "update" && context.state === "CURRENT" && this.request.localRules === undefined) return this.result(operation, "CURRENT", "verify", "AVAILABLE", plan); if (operation === "uninstall" && (context.state === "ABSENT" || context.state === "FRESH")) return this.result(operation, "ABSENT", "verify", "NOT_REQUIRED", plan);
      coordinator.checkpoint("plan"); this.request.onCheckpoint?.("beforeMutation"); coordinator.checkpoint("plan"); await this.withInstallationLock(context.target.installationAncestorPath, context.target.installationAncestorIdentity, () => this.performMutation(operation, context, coordinator)); return this.result(operation, operation === "uninstall" ? "ABSENT" : "CURRENT", "verify", "AVAILABLE", plan);
    } catch (error) { if (error instanceof SignalInterruption) throw new InterruptedFailure(error.signal, error.phase, "NOT_REQUIRED"); throw error; } finally { coordinator.dispose(); }
  }
  private async localRulesMutation(context: Context): Promise<LocalRulesMutation | undefined> {
    const releasePath = join(this.request.installationRoot, "releases", context.release.version); const targetPath = join(releasePath, "bundle", "agent-governance", context.release.localRulesPath); const previous = await optionalCanonicalLocalRules(targetPath); let source: Buffer | undefined;
    if (this.request.localRules !== undefined) source = await readCanonicalLocalRules(this.request.localRules, () => this.request.onCheckpoint?.("afterLocalRulesSourceOpen"));
    else if (context.current !== undefined && context.current.version !== context.release.version) { if (previous !== undefined) return undefined; const installed = await verifyRelease(join(this.request.installationRoot, "releases", context.current.version)); const liveSource = await optionalCanonicalLocalRules(join(this.request.installationRoot, "releases", context.current.version, "bundle", "agent-governance", installed.localRulesPath)); if (!matchesSnapshot(liveSource, context.installedLocalRules)) throw new Error("local rules changed since inspection"); source = liveSource; }
    if (source === undefined) return undefined; return { targetPath, source, ...(previous === undefined ? {} : { previous }) };
  }
  private async performMutation(operation: "install" | "update" | "uninstall", context: Context, coordinator: SignalCoordinator): Promise<void> {
    const root = this.request.installationRoot; const bindingId = this.bindingId(); const id = randomUUID(); const backupRoot = join(root, "backups", bindingId, id); const currentPath = this.currentPath(); const receiptPath = this.receiptPath(); const releasePath = join(root, "releases", context.release.version); const releaseExisted = await exists(releasePath); const localRules = operation === "uninstall" ? undefined : await this.localRulesMutation(context);
    await assertIdentity(context.target.installationAncestorPath, context.target.installationAncestorIdentity); await mkdir(root, { recursive: true, mode: 0o700 }); await ensureSafeDirectory(root); const installationIdentity = await captureIdentity(root); for (const path of [join(root, "backups"), join(root, "backups", bindingId), join(root, "releases"), join(root, "bindings"), this.bindingRoot()]) await ensureSafeDirectory(path); await mkdir(backupRoot, { mode: 0o700 });
    const current = await optionalBytes(currentPath); const appliedEntry = operation === "uninstall" ? removeManagedBlock(context.entry) : installManagedBlock(context.entry, context.binding); const appliedCurrent = operation === "uninstall" ? undefined : Buffer.from(`${JSON.stringify({ schemaVersion: 1, ...context.binding, targetRoot: this.request.targetRoot, entryFile: this.request.entryFile }, null, 2)}\n`); if (context.target.entryExists) await writeFile(join(backupRoot, "entry.bin"), context.entry, { flag: "wx", mode: 0o600 }); else await writeFile(join(backupRoot, "entry.absent"), "absent\n", { flag: "wx", mode: 0o600 }); if (current !== undefined) await writeFile(join(backupRoot, "current.json"), current, { flag: "wx", mode: 0o600 }); else await writeFile(join(backupRoot, "current.absent"), "absent\n", { flag: "wx", mode: 0o600 }); await writeFile(join(backupRoot, "entry.applied.bin"), appliedEntry, { flag: "wx", mode: 0o600 }); if (appliedCurrent !== undefined) await writeFile(join(backupRoot, "current.applied.json"), appliedCurrent, { flag: "wx", mode: 0o600 }); else await writeFile(join(backupRoot, "current.applied.absent"), "absent\n", { flag: "wx", mode: 0o600 });
    if (localRules !== undefined) { await writeFile(join(backupRoot, "local-rules.applied.bin"), localRules.source, { flag: "wx", mode: 0o600 }); if (localRules.previous !== undefined) await writeFile(join(backupRoot, "local-rules.bin"), localRules.previous, { flag: "wx", mode: 0o600 }); this.request.onCheckpoint?.("afterLocalRulesBackup"); }
    this.request.onCheckpoint?.("afterBackupWrites");
    if (context.target.entryExists ? !(await readFile(join(backupRoot, "entry.bin"))).equals(context.entry) : await readFile(join(backupRoot, "entry.absent"), "utf8") !== "absent\n") throw new Error("backup readback failed"); if (current !== undefined ? !(await readFile(join(backupRoot, "current.json"))).equals(current) : await readFile(join(backupRoot, "current.absent"), "utf8") !== "absent\n") throw new Error("backup readback failed"); if (!(await readFile(join(backupRoot, "entry.applied.bin"))).equals(appliedEntry) || (appliedCurrent !== undefined ? !(await readFile(join(backupRoot, "current.applied.json"))).equals(appliedCurrent) : await readFile(join(backupRoot, "current.applied.absent"), "utf8") !== "absent\n")) throw new Error("backup readback failed"); if (localRules !== undefined && !(await readFile(join(backupRoot, "local-rules.applied.bin"))).equals(localRules.source)) throw new Error("backup readback failed"); if (localRules?.previous !== undefined && !(await readFile(join(backupRoot, "local-rules.bin"))).equals(localRules.previous)) throw new Error("backup readback failed");
    const receipt: Receipt = { schemaVersion: 1, id, bindingId, status: "PREPARED", operation, backupRoot, entryPath: context.target.entryPath, entryExisted: context.target.entryExists, currentExisted: current !== undefined, releasePath, releaseExisted, localRulesPath: localRules?.targetPath ?? null, localRulesExisted: localRules?.previous !== undefined, entryBackupDigest: context.target.entryExists ? digest(context.entry) : null, currentBackupDigest: current === undefined ? null : digest(current), localRulesBackupDigest: localRules?.previous === undefined ? null : digest(localRules.previous), entryAppliedDigest: digest(appliedEntry), currentAppliedDigest: appliedCurrent === undefined ? null : digest(appliedCurrent), localRulesAppliedDigest: localRules === undefined ? null : digest(localRules.source) }; const prepared = Buffer.from(`${JSON.stringify(receipt)}\n`); await atomicWrite(join(backupRoot, "receipt.json"), prepared); await atomicWrite(receiptPath, prepared);
    this.request.onCheckpoint?.("afterReceipt"); await assertIdentity(root, installationIdentity);
    try { const liveEntry = await optionalBytes(context.target.entryPath); if (context.target.entryExists ? liveEntry === undefined || !liveEntry.equals(context.entry) : liveEntry !== undefined) throw new ConcurrentEntryChange("entry changed: identity changed, content changed, or no longer absent"); if (context.target.entryIdentity !== undefined) await assertIdentity(context.target.entryPath, context.target.entryIdentity); if (!matchesSnapshot(await optionalBytes(currentPath), current)) throw new Error("current metadata changed after backup"); if (localRules !== undefined && !matchesSnapshot(await optionalBytes(localRules.targetPath), localRules.previous)) throw new Error("local rules changed after backup"); } catch (error) { const rolled = Buffer.from(`${JSON.stringify({ ...receipt, status: "ROLLED_BACK" })}\n`); await atomicWrite(join(backupRoot, "receipt.json"), rolled); await atomicWrite(receiptPath, rolled); throw error; }
    let verifiedLocalRules: Buffer | undefined;
    try {
      coordinator.checkpoint("backup"); this.fault("backup"); await assertIdentity(this.request.targetRoot, context.target.targetIdentity); await assertIdentity(dirname(context.target.entryPath), context.target.entryParentIdentity);
      if (operation === "uninstall") { await atomicWrite(context.target.entryPath, appliedEntry); await rm(currentPath, { force: true }); }
      else { await this.activateRelease(context.release); if (localRules !== undefined) { if (localRules.previous === undefined) await atomicCreate(localRules.targetPath, localRules.source); else await atomicWrite(localRules.targetPath, localRules.source); } this.fault("stage"); if (current === undefined) await atomicCreate(currentPath, appliedCurrent!); else await atomicWrite(currentPath, appliedCurrent!); this.request.onCheckpoint?.("afterCurrent"); coordinator.checkpoint("activate"); if (!matchesSnapshot(await optionalBytes(currentPath), appliedCurrent)) throw new Error("current metadata postimage changed"); if (localRules !== undefined && !matchesSnapshot(await optionalBytes(localRules.targetPath), localRules.source)) throw new Error("local rules postimage changed"); const lateEntry = await optionalBytes(context.target.entryPath); if (context.target.entryExists ? lateEntry === undefined || !lateEntry.equals(context.entry) : lateEntry !== undefined) throw new ConcurrentEntryChange("entry changed before activation"); if (context.target.entryExists) await atomicWrite(context.target.entryPath, appliedEntry); else await atomicCreate(context.target.entryPath, appliedEntry); }
      this.request.onCheckpoint?.("afterEntry"); coordinator.checkpoint("activate"); this.fault("activate"); this.request.onCheckpoint?.("beforeVerification"); coordinator.checkpoint("verify"); if (!matchesSnapshot(await optionalBytes(context.target.entryPath), appliedEntry)) throw new Error("entry postimage changed"); if (!matchesSnapshot(await optionalBytes(currentPath), appliedCurrent)) throw new Error("current metadata postimage changed"); if (localRules !== undefined && !matchesSnapshot(await optionalBytes(localRules.targetPath), localRules.source)) throw new Error("local rules postimage changed"); if (operation === "uninstall") { const bytes = await readFile(context.target.entryPath); if (!removeManagedBlock(bytes).equals(bytes)) throw new Error("managed block remains after uninstall"); } else { verifyManagedBlock(await readFile(context.target.entryPath), context.binding); await verifyRelease(releasePath); verifiedLocalRules = await optionalCanonicalLocalRules(join(releasePath, "bundle", "agent-governance", context.release.localRulesPath)); } coordinator.checkpoint("verify"); this.fault("verify"); const committed = Buffer.from(`${JSON.stringify({ ...receipt, status: "COMMITTED" })}\n`); await atomicWrite(receiptPath, committed); this.request.onCheckpoint?.("afterCommitTopReceipt"); await atomicWrite(join(backupRoot, "receipt.json"), committed); try { if (!matchesSnapshot(await optionalBytes(context.target.entryPath), appliedEntry) || !matchesSnapshot(await optionalBytes(currentPath), appliedCurrent) || operation !== "uninstall" && !matchesSnapshot(await optionalCanonicalLocalRules(join(releasePath, "bundle", "agent-governance", context.release.localRulesPath)), verifiedLocalRules)) throw new Error("final commit joint postimage changed"); } catch (error) { await atomicWrite(join(backupRoot, "receipt.json"), prepared); await atomicWrite(receiptPath, prepared); throw error; }
    } catch (error) {
      try { this.request.onCheckpoint?.("duringRollback"); if (this.request.faultDuringRollback) throw new Error("injected rollback failure"); await this.restore(receipt, false, error instanceof ConcurrentEntryChange); } catch (rollbackError) { throw new InstallerFailure("ROLLBACK_FAILED", "rollback", "installation", "ROLLBACK_FAILED", `${(error as Error).message}; rollback failed: ${(rollbackError as Error).message}`, "FAILED"); }
      try { coordinator.checkpoint("rollback"); } catch (signal) { if (signal instanceof SignalInterruption) throw new InterruptedFailure(signal.signal, signal.phase, "SUCCEEDED"); throw signal; }
      if (error instanceof SignalInterruption) throw new InterruptedFailure(error.signal, error.phase, "SUCCEEDED"); throw new InstallerFailure("VERIFICATION_ROLLED_BACK", "verify", "installation", "VERIFICATION_ROLLED_BACK", (error as Error).message, "SUCCEEDED");
    }
  }
  private async activateRelease(release: VerifiedRelease): Promise<void> { const destination = join(this.request.installationRoot, "releases", release.version); if (await exists(destination)) { const installed = await verifyRelease(destination); if (installed.bundleDigest !== release.bundleDigest) throw new Error("release content changed without a version change"); return; } const stage = await mkdtemp(join(this.request.installationRoot, ".stage-")); await cp(join(this.request.releaseRoot, "bundle"), join(stage, "bundle"), { recursive: true, dereference: false, errorOnExist: true }); await cp(join(this.request.releaseRoot, "VERSION"), join(stage, "VERSION"), { errorOnExist: true }); await cp(join(this.request.releaseRoot, "release.files.sha256"), join(stage, "release.files.sha256"), { errorOnExist: true }); const verified = await verifyRelease(stage); if (verified.bundleDigest !== release.bundleDigest) throw new Error("staged release digest changed"); await rename(stage, destination); }
  private async otherBindingReferences(releasePath: string): Promise<boolean> { const bindings = join(this.request.installationRoot, "bindings"); for (const name of await readdir(bindings)) { if (name === this.bindingId()) continue; const root = join(bindings, name); const stat = await lstat(root); if (stat.isSymbolicLink() || !stat.isDirectory()) throw new Error("unsafe binding state directory"); const bytes = await optionalBytes(join(root, "current.json")); if (bytes === undefined) continue; const current = this.parseCurrent(bytes); if (join(this.request.installationRoot, "releases", current.version) === releasePath) return true; } return false; }
  private async verifiedBackup(receipt: Receipt, name: string, expectedDigest: string): Promise<Buffer> { await validateAllowedPath(receipt.backupRoot, join(this.request.installationRoot, "backups", receipt.bindingId), "directory"); const value = await requiredBytes(join(receipt.backupRoot, name), `${name} backup`); if (digest(value) !== expectedDigest) throw new Error(`${name} backup digest mismatch`); return value; }
  private async validateBackupEvidence(receipt: Receipt): Promise<void> { const absent = digest(Buffer.from("absent\n")); if (receipt.entryBackupDigest === null) await this.verifiedBackup(receipt, "entry.absent", absent); else await this.verifiedBackup(receipt, "entry.bin", receipt.entryBackupDigest); if (receipt.currentBackupDigest === null) await this.verifiedBackup(receipt, "current.absent", absent); else await this.verifiedBackup(receipt, "current.json", receipt.currentBackupDigest); await this.verifiedBackup(receipt, "entry.applied.bin", receipt.entryAppliedDigest); if (receipt.currentAppliedDigest === null) await this.verifiedBackup(receipt, "current.applied.absent", absent); else await this.verifiedBackup(receipt, "current.applied.json", receipt.currentAppliedDigest); if (receipt.localRulesBackupDigest !== null) await this.verifiedBackup(receipt, "local-rules.bin", receipt.localRulesBackupDigest); if (receipt.localRulesAppliedDigest !== null) await this.verifiedBackup(receipt, "local-rules.applied.bin", receipt.localRulesAppliedDigest); }
  private async restore(receipt: Receipt, validateCopies = true, preserveEntry = false): Promise<void> {
    if (validateCopies) { const top = await requiredBytes(this.receiptPath(), "transaction receipt"); const validated = await this.receiptWithMatchingBackup(top); if (JSON.stringify(validated) !== JSON.stringify(receipt)) throw new Error("transaction receipt copies differ"); }
    const entryBefore = receipt.entryBackupDigest === null ? undefined : await this.verifiedBackup(receipt, "entry.bin", receipt.entryBackupDigest); const entryApplied = await this.verifiedBackup(receipt, "entry.applied.bin", receipt.entryAppliedDigest); const currentBefore = receipt.currentBackupDigest === null ? undefined : await this.verifiedBackup(receipt, "current.json", receipt.currentBackupDigest); const currentApplied = receipt.currentAppliedDigest === null ? undefined : await this.verifiedBackup(receipt, "current.applied.json", receipt.currentAppliedDigest); const localBefore = receipt.localRulesBackupDigest === null ? undefined : await this.verifiedBackup(receipt, "local-rules.bin", receipt.localRulesBackupDigest); const localApplied = receipt.localRulesAppliedDigest === null ? undefined : await this.verifiedBackup(receipt, "local-rules.applied.bin", receipt.localRulesAppliedDigest); const shared = await this.otherBindingReferences(receipt.releasePath); const liveEntry = await optionalBytes(receipt.entryPath); const liveCurrent = await optionalBytes(this.currentPath());
    if (!preserveEntry && !matchesSnapshot(liveEntry, entryApplied) && !matchesSnapshot(liveEntry, entryBefore)) throw new Error("entry changed; stale rollback state"); if (!matchesSnapshot(liveCurrent, currentApplied) && !matchesSnapshot(liveCurrent, currentBefore)) throw new Error("current metadata changed; stale rollback state");
    let liveLocal: Buffer | undefined; if (!shared && receipt.localRulesPath !== null) { liveLocal = await optionalBytes(receipt.localRulesPath); if (!matchesSnapshot(liveLocal, localApplied) && !matchesSnapshot(liveLocal, localBefore)) throw new Error("local rules changed; stale shared state"); }
    if (!shared && !receipt.releaseExisted && await exists(receipt.releasePath)) await verifyRelease(receipt.releasePath);
    this.request.onCheckpoint?.("beforeRollbackEntry"); const entryNow = await optionalBytes(receipt.entryPath); if (!preserveEntry && !matchesSnapshot(entryNow, entryApplied) && !matchesSnapshot(entryNow, entryBefore)) throw new Error("entry changed; stale rollback state"); if (!preserveEntry && !matchesSnapshot(entryNow, entryBefore)) { if (entryBefore !== undefined) await atomicWrite(receipt.entryPath, entryBefore); else await rm(receipt.entryPath, { force: true }); } if (!preserveEntry && !matchesSnapshot(await optionalBytes(receipt.entryPath), entryBefore)) throw new Error("entry restore postimage changed"); this.request.onCheckpoint?.("afterRollbackEntry");
    const currentNow = await optionalBytes(this.currentPath()); if (!matchesSnapshot(currentNow, currentApplied) && !matchesSnapshot(currentNow, currentBefore)) throw new Error("current metadata changed; stale rollback state"); if (!matchesSnapshot(currentNow, currentBefore)) { if (currentBefore !== undefined) await atomicWrite(this.currentPath(), currentBefore); else await rm(this.currentPath(), { force: true }); } if (!matchesSnapshot(await optionalBytes(this.currentPath()), currentBefore)) throw new Error("current metadata restore postimage changed"); this.request.onCheckpoint?.("afterRollbackCurrent"); if (!matchesSnapshot(await optionalBytes(this.currentPath()), currentBefore) || !preserveEntry && !matchesSnapshot(await optionalBytes(receipt.entryPath), entryBefore)) throw new Error("restore joint postimage changed");
    if (!shared && receipt.localRulesPath !== null) { const localNow = await optionalBytes(receipt.localRulesPath); if (!matchesSnapshot(localNow, localApplied) && !matchesSnapshot(localNow, localBefore)) throw new Error("local rules changed; stale shared state"); if (receipt.releaseExisted && !matchesSnapshot(localNow, localBefore)) { if (localBefore !== undefined) await atomicWrite(receipt.localRulesPath, localBefore); else await rm(receipt.localRulesPath, { force: true }); } if (receipt.releaseExisted && !matchesSnapshot(await optionalBytes(receipt.localRulesPath), localBefore)) throw new Error("local rules restore postimage changed"); }
    if (!shared && !receipt.releaseExisted && await exists(receipt.releasePath)) { if (receipt.localRulesPath !== null) { const localNow = await optionalBytes(receipt.localRulesPath); if (!matchesSnapshot(localNow, localApplied) && !matchesSnapshot(localNow, localBefore)) throw new Error("local rules changed; stale shared state"); } await verifyRelease(receipt.releasePath); await rm(receipt.releasePath, { recursive: true }); }
    if (!preserveEntry && !matchesSnapshot(await optionalBytes(receipt.entryPath), entryBefore) || !matchesSnapshot(await optionalBytes(this.currentPath()), currentBefore) || !shared && receipt.localRulesPath !== null && !matchesSnapshot(await optionalBytes(receipt.localRulesPath), localBefore)) throw new Error("restore final joint postimage changed"); const rolled = Buffer.from(`${JSON.stringify({ ...receipt, status: "ROLLED_BACK" })}\n`); await atomicWrite(join(receipt.backupRoot, "receipt.json"), rolled); this.request.onCheckpoint?.("afterRollbackBackupReceipt"); await atomicWrite(this.receiptPath(), rolled);
  }
  async rollback(): Promise<InstallResult> { const coordinator = new SignalCoordinator(this.request.signalSource); let restoreVerified = false; coordinator.start(); try { const target = await inspectTarget(this.request.targetRoot, this.request.entryFile, this.request.installationRoot); const bytes = await optionalBytes(this.receiptPath()); if (bytes === undefined) throw new Error("rollback receipt is missing"); const receipt = await this.receiptWithMatchingBackup(bytes); coordinator.checkpoint("rollback"); if (this.request.dryRun) return this.result("rollback", "RECOVERY_REQUIRED", "plan", "AVAILABLE"); if (receipt.status !== "ROLLED_BACK") await this.withInstallationLock(target.installationAncestorPath, target.installationAncestorIdentity, async () => { await assertIdentity(target.targetRoot, target.targetIdentity); await assertIdentity(dirname(target.entryPath), target.entryParentIdentity); if (target.entryIdentity !== undefined) await assertIdentity(target.entryPath, target.entryIdentity); await this.restore(receipt); }, true); const restored = await this.context(); if (["TAMPERED", "RECOVERY_REQUIRED"].includes(restored.state)) throw new Error(`rollback verification failed: ${restored.state}`); restoreVerified = true; coordinator.checkpoint("rollback"); return this.result("rollback", restored.state, "rollback", "SUCCEEDED"); } catch (error) { if (error instanceof SignalInterruption) throw new InterruptedFailure(error.signal, error.phase, restoreVerified ? "SUCCEEDED" : "NOT_REQUIRED"); throw error; } finally { coordinator.dispose(); } }
}
